# Generated by Django 5.1.4 on 2024-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=10, unique=True)),
                ('availability', models.CharField(choices=[('OK', 'Available'), ('Down', 'Out of Service'), ('Maintenance', 'Under Maintenance')], max_length=12)),
                ('charging_power', models.FloatField()),
                ('max_power', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
