# Generated by Django 5.1.3 on 2025-02-20 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='charging_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
    ]
