# Generated by Django 5.1.4 on 2024-12-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingschedule',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='drivingschedule',
            name='route_id',
        ),
    ]
