# Generated by Django 5.1.4 on 2024-12-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schedule', '0002_remove_drivingschedule_driver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_version', models.IntegerField()),
                ('type_number', models.IntegerField()),
                ('short_code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='drivingschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='drivingschedule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='drivingschedule',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drivingschedule',
            name='bus_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='drivingschedule',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='driving_schedule.locationtype'),
        ),
    ]
