# Generated by Django 5.1.4 on 2024-12-18 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMonitoring', '0001_initial'),
        ('driving_schedule', '0003_locationtype_remove_drivingschedule_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingschedule',
            name='bus_id',
        ),
        migrations.AddField(
            model_name='drivingschedule',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='busMonitoring.electricbus'),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
