# Generated by Django 5.1.4 on 2024-12-18 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMonitoring', '0001_initial'),
        ('driving_schedule', '0004_remove_drivingschedule_bus_id_drivingschedule_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingschedule',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driving_schedules', to='busMonitoring.electricbus'),
        ),
    ]
