# Generated by Django 5.1.4 on 2024-12-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schedule', '0005_alter_drivingschedule_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingschedule',
            name='arrival_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_schedules', to='driving_schedule.locationtype'),
        ),
        migrations.AddField(
            model_name='drivingschedule',
            name='departure_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_schedules', to='driving_schedule.locationtype'),
        ),
    ]
