# Generated by Django 5.1.4 on 2024-12-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schedule', '0006_drivingschedule_arrival_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivingschedule',
            old_name='location_name',
            new_name='arr_location_name',
        ),
        migrations.RemoveField(
            model_name='drivingschedule',
            name='location_type',
        ),
        migrations.AddField(
            model_name='drivingschedule',
            name='dep_location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
