# Generated by Django 5.1.4 on 2024-12-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schedule', '0007_rename_location_name_drivingschedule_arr_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtype',
            name='short_code',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='type_number',
        ),
    ]
