# Generated by Django 5.1.4 on 2024-12-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schedule', '0008_remove_locationtype_short_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingschedule',
            name='arr_location_name',
        ),
        migrations.RemoveField(
            model_name='drivingschedule',
            name='dep_location_name',
        ),
        migrations.AddField(
            model_name='locationtype',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
