# Generated by Django 5.1.4 on 2025-01-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_schedule', '0004_alter_locationtype_description'),
        ('driving_schedule', '0010_remove_locationtype_basis_version'),
    ]

    operations = [
    ]
