# Generated by Django 5.1.3 on 2024-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricbus',
            name='vehicle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
