# Generated by Django 5.1.3 on 2024-12-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMonitoring', '0002_electricbus_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricbus',
            name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='electricbus',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='electricbus',
            name='CAP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='electricbus',
            name='ENE',
            field=models.IntegerField(),
        ),
    ]
