# Generated by Django 5.1.3 on 2024-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busMonitoring', '0003_remove_electricbus_vehicle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbus',
            name='battery',
            field=models.IntegerField(),
        ),
    ]
