# Generated by Django 5.1.3 on 2024-12-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busMonitoring', '0004_alter_electricbus_battery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricbus',
            old_name='charging_location',
            new_name='charging_point',
        ),
        migrations.RenameField(
            model_name='electricbus',
            old_name='charging_start',
            new_name='session_start',
        ),
    ]
